# Site settings
title: SOARlab
email: zvonimir@cs.utah.edu
description: "Software Analysis Research Laboratory, School of Computing, University of Utah"
baseurl: ""
url: "https://soarlab.org"
twitter_username: soarlab
github_username: soarlab
youtube_username: 
facebook_page:
safe: false
lsi: false
google_analytics: #"'UA-69348306-1'"
use_analytics: false

paper_content_url: ["/PDFs/"]

plugins:
  - jekyll-redirect-from

# Build settings
permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", ".idea/"]

include: ["/PDFs/"]

# Collections
collections:
  persons:
    output: true
  publications:
    output: true
    permalink: /publications/:path/
  videos:
    output: false
  institutions:
    output: false
  projects:
    output: true
  talks:
    output: false

